### ISSUE TITLE
Fails at some point...

### ISSUE THREAD

**Issue by JaxonBP** [davidshaw/Tumblr-Scrape#1]
Hi, I running into a problem with this script - as it fails after downloading 14 pictures. Any idea of what could be the problem?

[+] scraping page 1
[+] wrote pic 1
[+] wrote pic 2
[+] wrote pic 3
[+] wrote pic 4
[+] wrote pic 5
[+] wrote pic 6
[+] wrote pic 7
[+] wrote pic 8
[+] wrote pic 9
[+] scraping page 2
[+] wrote pic 10
[+] wrote pic 11
[+] wrote pic 12
[+] wrote pic 13
[+] wrote pic 14
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/uri/common.rb:436:in `split': bad URI(is not URI?): http://29.media.tumblr.com/tumblr_lsker1kOZY1r3if7bo1_500.jpg"><img class="roundedtop" src="http://25.media.tumblr.com/tumblr_lx6xxbx8wf1qjx9n8o1_500.jpg (URI::InvalidURIError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/uri/common.rb:485:in`parse'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:29:in `open'
    from tumblr_scrape.rb:42
    from tumblr_scrape.rb:40:in`each'
    from tumblr_scrape.rb:40

**Comment by jharris847** [comment]
Regex fails if the image is listed on the same line twice. Regex as written is greedy, so it finds (in the above example) `http://29.media.tumblr.com/tumblr(*.).(jpg|png)" The (.*) on this example contains "lsker1kOZY1r3if7bo1_500.jpg"><img class="roundedtop" src="http://25.media.tumblr.com/tumblr_lx6xxbx8wf1qjx9n8o1_500"`

Regex needs to look for the tumblr portion, then collect anything that isn't `"` until it ends with `.(jpg|png)`

Change the regex on line 5 to

``` ruby
regex = /http:\/\/\d+\.media\.tumblr\.com\/tumblr_[^"]*.(jpg|png)/
```
